# Generated by Django 3.2.8 on 2021-10-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('nom_utilisateur', models.CharField(blank=True, max_length=20, null=True)),
                ('mot_de_passe', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
